### PR TITLE
Python 3

### PR DESCRIPTION
**Pull request by laerreal**
I have managed to make `pyrsp` working under Python 3 (3.5.2 actually).
Please read commit messages for explanation of corresponding changes.

Also note that because of rebasing in course of patch preparation, GitHub
may confuse the patch order.

### CODE REVIEW

**Comment by stef** [comment]
wow.

**Comment by laerreal** [comment]
Fixed "python3 -m unittest test" command from a terminal.
I normally launched the tests from Eclipse IDE, so I missed that problem.

**Comment by stef** [comment]
i tested it under py 3.7, and made only two small changes. one is the joining of the printout in dump_mpu() into one line, and the other is related to the loading of the virtualenv at the beginning of rsp.py, it seems that py3 does not implement execfile anymore. i really hate py3.

Vasily thank you very much for this monster of a patch, must have been agony to put all those () in the prints and the b prefixes to strings.

<3

**Comment by stef** [comment]
i also bumped the version to 0.4 and pushed a pkg to pypi.

**Comment by stef** [comment]
and sorry for this taking so long. somehow i thought i already merged this and forgot about it, only today i noticed that this is still pending.

**Comment by laerreal** [comment]
Good =)

**Pull request merged**
